routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('rubros', App\Http\Controllers\RubroController::class);


Route::resource('empresas', App\Http\Controllers\EmpresaController::class);


Route::resource('profesions', App\Http\Controllers\ProfesionController::class);


Route::resource('profesionals', App\Http\Controllers\ProfesionalController::class);


Route::resource('especialidads', App\Http\Controllers\EspecialidadController::class);


Route::resource('sucursals', App\Http\Controllers\SucursalController::class);


Route::resource('feriados', App\Http\Controllers\FeriadoController::class);


Route::resource('parametrizacionTurnos', App\Http\Controllers\ParametrizacionTurnoController::class);

Route::resource('dias', App\Http\Controllers\DiaController::class);

Route::get('parametrizacionTurnos/{id}/visualizarTurnos', [App\Http\Controllers\ParametrizacionTurnoController::class,'visualizarTurnos'])
    ->name('parametrizacionTurnos.visualizarTurnos');

Route::get('parametrizacionTurnos/{id}/generarTurnos', [App\Http\Controllers\ParametrizacionTurnoController::class,'generarTurnos'])
    ->name('parametrizacionTurnos.generarTurnos');    


Route::resource('turnos', App\Http\Controllers\TurnoController::class);


Route::resource('tipoInstalacions', App\Http\Controllers\TipoInstalacionController::class);


Route::resource('instalacions', App\Http\Controllers\InstalacionController::class);


Route::resource('reservas', App\Http\Controllers\ReservaController::class);

Route::post('reservas/{id}/cancelar', [App\Http\Controllers\ReservaController::class,'cancelar'])->name('reservas.cancelar'); 

Route::resource('agenda', App\Http\Controllers\AgendaController::class);

Route::get('agenda/{id}/ausente', [App\Http\Controllers\AgendaController::class,'ausente'])->name('agenda.ausente');

Route::get('agenda/{id}/presente', [App\Http\Controllers\AgendaController::class,'presente'])->name('agenda.presente');        


Route::resource('users', App\Http\Controllers\UserController::class)->middleware('auth');

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\AgendaDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateReservaRequest;
use App\Http\Requests\UpdateReservaRequest;
use App\Repositories\ReservaRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class AgendaController extends AppBaseController
{
    /** @var  ReservaRepository */
    private $ReservaRepository;

    public function __construct(ReservaRepository $reservasRepo)
    {
        $this->ReservaRepository = $reservasRepo;
    }

    /**
     * Display a listing of the agenda.
     *
     * @param reservaDataTable $reservaDataTable
     * @return Response
     */
    public function index(AgendaDataTable $agendaDataTable)
    {
        return $agendaDataTable->render('agenda.index');
    }

    /**
     * Display the specified agenda.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $reserva = $this->ReservaRepository->find($id);

        if (empty($reserva)) {
            Flash::error('Agenda no encontrada');

            return redirect(route('agenda.index'));
        }

        return view('agenda.show')->with('reserva', $reserva);
    }

    /**
     * Update the specified Agenda in storage.
     *
     * @param  int              $id     
     *
     * @return Response
     */
    public function ausente($id)
    {        

        $reserva = $this->ReservaRepository->find($id);

        if (empty($reserva)) {
            Flash::error('Agenda no encontrada');

            return redirect(route('agenda.index'));
        }

        $reserva = $this->ReservaRepository->update($request->all(), $id);

        Flash::success('Agenda actualizada correctamente.');

        return redirect(route('agenda.index'));
    }

    /**
     * Update the specified Agenda in storage.
     *
     * @param  int              $id    
     * 
     * @return Response
     */
    public function presente($id)
    {        
        $reserva = $this->ReservaRepository->find($id);

        if (empty($reserva)) {
            Flash::error('Agenda no encontrada');

            return redirect(route('agenda.index'));
        }

        $reserva = $this->ReservaRepository->update($request->all(), $id);

        Flash::success('Agenda actualizada correctamente.');

        return redirect(route('agenda.index'));
    }

}

resources/views/agenda/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Listado Reservas</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'agenda.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('agenda.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('agenda.index') }}" class="btn btn-default">Cancelar</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/agenda/datatables_actions.blade.php
{!! Form::open(['route' => ['agenda.destroy', $id], 'method' => 'delete']) !!}
<style type="text/css">    
    a .btn{
        padding: 0 !important;
        font-size: .9rem;
        border: 1px solid indianred;
        background: indianred;        
    }

    .btn > span {
        display: inline-flex;
        color: white;
    }

    .btn > span > p{
        margin-left: 2px;
        margin: 0;
        line-height: 1.2;
    }


@media (max-width:480px)  { 
/* smartphones, Android phones, landscape iPhone */ 
    .btn > span > p{
        display: none;
    }

    .dt-buttons{
        display: none;
    }
}
    
</style>

<div class='btn-group'>    
    <a href="{{ route('agenda.presente', $id) }}" class='btn btn-default btn-xs botones-accion' style="background: forestgreen;">
        <!-- <i class="fa fa-edit"></i> -->
        <span>
            <i class="fas fa-user"></i>
            <p>PRESENTE</p>
        </span>
    </a>
    <a href="{{ route('agenda.ausente', $id) }}" class='btn btn-default btn-xs botones-accion' style="background: indianred;">
        <!-- <i class="fa fa-eye"></i> -->
        <span>
            <i class="fas fa-user-slash"></i>
            <p>AUSENTE</p>
        </span>
    </a>
   
</div>
{!! Form::close() !!}

resources/views/agenda/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Editar Agenda</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($listadoReservas, ['route' => ['agenda.update', $listadoReservas->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('agenda.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('agenda.index') }}" class="btn btn-default">Cancelar</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/agenda/fields.blade.php
<!-- Usuario Field -->
<div class="form-group col-sm-6">
    {!! Form::label('usuario', 'Usuario:') !!}
    {!! Form::text('usuario', null, ['class' => 'form-control']) !!}
</div>

<!-- Fecha Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fecha', 'Fecha:') !!}
    {!! Form::text('fecha', null, ['class' => 'form-control','id'=>'fecha']) !!}
</div>

@push('page_scripts')
    <script type="text/javascript">
        $('#fecha').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Hora Field -->
<div class="form-group col-sm-6">
    {!! Form::label('hora', 'Hora:') !!}
    {!! Form::text('hora', null, ['class' => 'form-control']) !!}
</div>

<!-- Profesional Field -->
<div class="form-group col-sm-6">
    {!! Form::label('profesional', 'Profesional:') !!}
    {!! Form::text('profesional', null, ['class' => 'form-control']) !!}
</div>

<!-- Especialidad Field -->
<div class="form-group col-sm-6">
    {!! Form::label('especialidad', 'Especialidad:') !!}
    {!! Form::text('especialidad', null, ['class' => 'form-control']) !!}
</div>

<!-- Estado Field -->
<div class="form-group col-sm-6">
    {!! Form::label('estado', 'Estado:') !!}
    {!! Form::text('estado', null, ['class' => 'form-control']) !!}
</div>

resources/views/agenda/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Agenda</h1>
                </div>
                <div class="col-sm-6">
                    <!-- <a class="btn btn-primary float-right"
                       href="{{ route('agenda.create') }}">
                        Nuevo
                    </a> -->
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('agenda.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/agenda/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Detalle Turno</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('agenda.index') }}">
                        Volver
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('agenda.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/agenda/show_fields.blade.php
<!-- Usuario Field -->
<div class="col-sm-12">
    {!! Form::label('usuario', 'Usuario:') !!}
    <p>{{ $listadoReservas->usuario }}</p>
</div>

<!-- Fecha Field -->
<div class="col-sm-12">
    {!! Form::label('fecha', 'Fecha:') !!}
    <p>{{ $listadoReservas->fecha }}</p>
</div>

<!-- Hora Field -->
<div class="col-sm-12">
    {!! Form::label('hora', 'Hora:') !!}
    <p>{{ $listadoReservas->hora }}</p>
</div>

<!-- Profesional Field -->
<div class="col-sm-12">
    {!! Form::label('profesional', 'Profesional:') !!}
    <p>{{ $listadoReservas->profesional }}</p>
</div>

<!-- Especialidad Field -->
<div class="col-sm-12">
    {!! Form::label('especialidad', 'Especialidad:') !!}
    <p>{{ $listadoReservas->especialidad }}</p>
</div>

<!-- Estado Field -->
<div class="col-sm-12">
    {!! Form::label('estado', 'Estado:') !!}
    <p>{{ $listadoReservas->estado }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $listadoReservas->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $listadoReservas->updated_at }}</p>
</div>

resources/views/agenda/table.blade.php
@push('third_party_stylesheets')
    @include('layouts.datatables_css')
@endpush

<style type="text/css">
    
    .table-responsive {
    width: 100%;
    margin-bottom: 15px;
    overflow-y: hidden;
    -ms-overflow-style: -ms-autohiding-scrollbar;
    border: 1px solid #ddd;
}
</style>
<div class="table-responsive">
{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('third_party_scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush