routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('rubros', App\Http\Controllers\RubroController::class);


Route::resource('empresas', App\Http\Controllers\EmpresaController::class);


Route::resource('profesions', App\Http\Controllers\ProfesionController::class);


Route::resource('profesionals', App\Http\Controllers\ProfesionalController::class);


Route::resource('especialidads', App\Http\Controllers\EspecialidadController::class);


Route::resource('sucursals', App\Http\Controllers\SucursalController::class);


Route::resource('feriados', App\Http\Controllers\FeriadoController::class);


Route::resource('parametrizacionTurnos', App\Http\Controllers\ParametrizacionTurnoController::class);

Route::resource('dias', App\Http\Controllers\DiaController::class);

Route::get('parametrizacionTurnos/{id}/visualizarTurnos', [App\Http\Controllers\ParametrizacionTurnoController::class,'visualizarTurnos'])
    ->name('parametrizacionTurnos.visualizarTurnos');

Route::get('parametrizacionTurnos/{id}/generarTurnos', [App\Http\Controllers\ParametrizacionTurnoController::class,'generarTurnos'])
    ->name('parametrizacionTurnos.generarTurnos');    


Route::resource('turnos', App\Http\Controllers\TurnoController::class);


Route::resource('tipoInstalacions', App\Http\Controllers\TipoInstalacionController::class);


Route::resource('instalacions', App\Http\Controllers\InstalacionController::class);


Route::resource('reservas', App\Http\Controllers\ReservaController::class);

Route::post('reservas/{id}/cancelar', [App\Http\Controllers\ReservaController::class,'cancelar'])->name('reservas.cancelar'); 

Route::resource('agenda', App\Http\Controllers\AgendaController::class);

Route::get('agenda/{id}/ausente', [App\Http\Controllers\AgendaController::class,'ausente'])->name('agenda.ausente');

Route::get('agenda/{id}/presente', [App\Http\Controllers\AgendaController::class,'presente'])->name('agenda.presente');        


Route::resource('users', App\Http\Controllers\UserController::class)->middleware('auth');

app/Models/Dia.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class Dia
 * @package App\Models
 * @version October 11, 2021, 11:47 am UTC
 *
 * @property string $nombre
 */
class Dia extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'dias';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'nombre'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nombre' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nombre' => 'required|max:10'
    ];

    function getAbreviaturaAttribute(){
        return substr($this->nombre, 0, 2);
    }

    
}

app/Models/Profesional.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Models\Empresa;
use App\Models\Profesional;
use App\Models\Especialidad;

/**
 * Class Profesional
 * @package App\Models
 * @version October 8, 2021, 10:54 pm UTC
 *
 * @property string $nombre
 * @property string $apellido
 * @property string $matricula
 * @property integer $dni
 * @property string $calle
 */
class Profesional extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'profesionales';
    

    protected $dates = ['deleted_at'];

    protected $hidden = ['pivot'];

    public $fillable = [
        'nombre',
        'apellido',
        'matricula',
        'dni',
        'calle',
        'altura',
        'departamento',
        'id_empresa'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nombre' => 'string',
        'apellido' => 'string',
        'matricula' => 'string',
        'dni' => 'integer',
        'calle' => 'string',
        'altura' => 'integer',
        'departamento' => 'string',
        'id_empresa' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nombre' => 'required|max:255',
        'apellido' => 'required|max:255',
        'matricula' => 'max:255',
        'dni' => 'required|numeric|min:5000000|max:80000000',
        'calle' => 'max:255',
        'altura' => 'nullable|numeric|max:8000000',
        'departamento' => 'max:20',
    ];

    public function getFullNameAttribute()
    {
        return $this->nombre . ' ' . $this->apellido;
    }

    public function empresa()
    {
        return $this->belongsTo(Empresa::class, 'id', 'id_empresa');
    }

    public function profesiones()
    {
        return $this->belongsToMany(Profesion::class,'profesionales_profesiones','id_profesional','id_profesion');
    }

    public function especialidades()
    {
        return $this->belongsToMany(Especialidad::class,'profesionales_especialidades','id_profesional','id_especialidad');
    }

}

app/Http/Controllers/ParametrizacionTurnoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateParametrizacionTurnoRequest;
use App\Http\Requests\UpdateParametrizacionTurnoRequest;
use App\Repositories\ParametrizacionTurnoRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use Auth;
use Carbon\CarbonPeriod;
use Carbon\Carbon;
use App\Models\Turno;
use App\Models\Feriado;

class ParametrizacionTurnoController extends AppBaseController
{
    /** @var  ParametrizacionTurnoRepository */
    private $parametrizacionTurnoRepository;

    public function __construct(ParametrizacionTurnoRepository $parametrizacionTurnoRepo)
    {
        $this->parametrizacionTurnoRepository = $parametrizacionTurnoRepo;
    }

    /**
     * Display a listing of the ParametrizacionTurno.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $parametrizacionTurnos = $this->parametrizacionTurnoRepository->all();

        return view('parametrizacion_turnos.index')
            ->with('parametrizacionTurnos', $parametrizacionTurnos);
    }

    /**
     * Show the form for creating a new ParametrizacionTurno.
     *
     * @return Response
     */
    public function create()
    {
        $user=Auth::user();

        $sucursales = $user->empresa->sucursales->pluck('nombre','id');
        

        return view('parametrizacion_turnos.create')
            ->with('sucursales',$sucursales);
    }

    /**
     * Store a newly created ParametrizacionTurno in storage.
     *
     * @param CreateParametrizacionTurnoRequest $request
     *
     * @return Response
     */
    public function store(CreateParametrizacionTurnoRequest $request)
    {
        $input = $request->all();

        $input['sobreturnos'] = 0;
        $parametrizacionTurno = $this->parametrizacionTurnoRepository->create($input);

        Flash::success('Parametrizacion Turno guardado de forma correcta.');

        return redirect(route('parametrizacionTurnos.index'));
    }

    /**
     * Display the specified ParametrizacionTurno.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $parametrizacionTurno = $this->parametrizacionTurnoRepository->find($id);

        if (empty($parametrizacionTurno)) {
            Flash::error('Parametrizacion Turno no encontrado');

            return redirect(route('parametrizacionTurnos.index'));
        }

        return view('parametrizacion_turnos.show')->with('parametrizacionTurno', $parametrizacionTurno);
    }

    /**
     * Show the form for editing the specified ParametrizacionTurno.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $parametrizacionTurno = $this->parametrizacionTurnoRepository->find($id);

        $user=Auth::user();

        $sucursales = $user->empresa->sucursales->pluck('nombre','id');

        if (empty($parametrizacionTurno)) {
            Flash::error('Parametrizacion Turno no encontrado');

            return redirect(route('parametrizacionTurnos.index'));
        }

        return view('parametrizacion_turnos.edit')
            ->with('parametrizacionTurno', $parametrizacionTurno)
            ->with('sucursales', $sucursales);
    }

    /**
     * Update the specified ParametrizacionTurno in storage.
     *
     * @param int $id
     * @param UpdateParametrizacionTurnoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateParametrizacionTurnoRequest $request)
    {
        $parametrizacionTurno = $this->parametrizacionTurnoRepository->find($id);

        if (empty($parametrizacionTurno)) {
            Flash::error('Parametrizacion Turno no encontrado');

            return redirect(route('parametrizacionTurnos.index'));
        }

        if ($parametrizacionTurno->generado) {
            Flash::error('No se puede editar una parametrización generada');

            return redirect(route('parametrizacionTurnos.index'));
        }

        $input = $request->all();
        $input['sobreturnos'] = 0;

        $parametrizacionTurno = $this->parametrizacionTurnoRepository->update($input, $id);

        Flash::success('Parametrizacion Turno actualizado de forma correcta.');

        return redirect(route('parametrizacionTurnos.index'));
    }

    /**
     * Remove the specified ParametrizacionTurno from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $parametrizacionTurno = $this->parametrizacionTurnoRepository->find($id);

        if (empty($parametrizacionTurno)) {
            Flash::error('Parametrizacion Turno no encontrado');

            return redirect(route('parametrizacionTurnos.index'));
        }

        if ($parametrizacionTurno->generado) {
            Flash::error('No se puede eliminar una parametrización generada');

            return redirect(route('parametrizacionTurnos.index'));
        }

        $this->parametrizacionTurnoRepository->delete($id);

        Flash::success('Parametrizacion Turno borrado de forma correcta.');

        return redirect(route('parametrizacionTurnos.index'));
    }

     /**
     * Show the turnos for the specified ParametrizacionTurno.
     * ref: https://stackoverflow.com/a/65422833
     * ref: https://stackoverflow.com/a/50854594
     *
     * @param int $id
     *
     * @return Response
     */
    public function visualizarTurnos($id)
    {
        $param = $this->parametrizacionTurnoRepository->find($id);

        if (empty($param)) {
            Flash::error('Parametrizacion Turno no encontrado');

            return redirect(route('parametrizacionTurnos.index'));
        }

        if($param->generado){
            Flash::error('Ya se generarón los Turnos de esa parametrización');

            return redirect(route('parametrizacionTurnos.index'));
        }

        $dias = CarbonPeriod::create($param->fecha_desde, $param->fecha_hasta);
        $horarios = new CarbonPeriod($param->hora_desde, $param->duracion_turno.' minutes', $param->hora_hasta); // for create use 24 hours format later change format 
        $turnos = new \Illuminate\Database\Eloquent\Collection;
        $feriados = new \Illuminate\Database\Eloquent\Collection;
        $solapados = new \Illuminate\Database\Eloquent\Collection;
        //dd($horarios);
        $dias_semana = explode(',', $param->dias);

        foreach ($dias as $fecha) {
        
            if( in_array($this->dayOfWeek($fecha),$dias_semana) ){

                foreach($horarios as $hora){
                    
                    $hora_hasta = $hora->toImmutable()->addMinutes($param->duracion_turno); //inmutable para que no me modifique el objeto $hora
                    $ultimo_turno = Carbon::createFromFormat('Y-m-d H:i:s', $fecha->format('Y-m-d') . ' '.$param->hora_hasta );

                    if( $hora_hasta->lessThanOrEqualTo($ultimo_turno) ){        //si el turno termina mas alla de la hora hasta no lo agrego
                        
                        $turno = new Turno([
                            'fecha'             => $fecha->format('Y-m-d'),
                            'hora_desde'        => $hora->format("h:i"),
                            'hora_hasta'        => $hora_hasta->format("h:i"),                        
                            'duracion'          => $param->duracion_turno,                            
                            'id_sucursal'       => $param->id_sucursal,
                            'id_profesional'    => $param->id_profesional,
                            'id_especialidad'   => $param->id_especialidad,
                            'sobreturnos'       => $param->sobreturnos,
                            'id_parametrizacion' => $param->id,
                            'test' => 'test'
                        ]);
                        
                        //si es feriado el dia lo excluyo
                        if(Feriado::esFeriado($param->id_sucursal, $fecha, $hora)){
                            $feriados->push($turno);
                        }else{
                            if($turno->haySolapamiento())
                                $solapados->push($turno);
                            else
                                $turnos->push($turno);
                        }

                    }
                }
            }
        }

        return view('parametrizacion_turnos.visualizar_turnos')
            ->with('parametrizacionTurno', $param)
            ->with('turnos', $turnos)
            ->with('feriados', $feriados)
            ->with('solapados', $solapados);
    }

    /**
     * Show the form for editing the specified ParametrizacionTurno.
     *
     * @param int $id
     *
     * @return Response
     */
    public function generarTurnos($id)
    {
        $param = $this->parametrizacionTurnoRepository->find($id);

        $user=Auth::user();

        $sucursales = $user->empresa->sucursales->pluck('nombre','id');
        
        if (empty($param)) {
            Flash::error('Parametrizacion Turno no encontrado');

            return redirect(route('parametrizacionTurnos.index'));
        }

        $dias = CarbonPeriod::create($param->fecha_desde, $param->fecha_hasta);
        $horarios = new CarbonPeriod($param->hora_desde, $param->duracion_turno.' minutes', $param->hora_hasta); // for create use 24 hours format later change format 
     
        $dias_semana = explode(',', $param->dias);

        foreach ($dias as $fecha) {
        
            if( in_array($this->dayOfWeek($fecha),$dias_semana) ){

                foreach($horarios as $hora){
                    
                    $hora_hasta = $hora->toImmutable()->addMinutes($param->duracion_turno); //inmutable para que no me modifique el objeto $hora

resources/views/parametrizacion_turnos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Crear Parametrización de Turno</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'parametrizacionTurnos.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('parametrizacion_turnos.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('parametrizacionTurnos.index') }}" class="btn btn-default">Cancelar</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/parametrizacion_turnos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Editar Parametrización de Turno</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($parametrizacionTurno, ['route' => ['parametrizacionTurnos.update', $parametrizacionTurno->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('parametrizacion_turnos.fields')
                </div>
            </div>

            <div class="card-footer">
            @if(!$parametrizacionTurno->generado)
                {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
            @endif
                <a href="{{ route('parametrizacionTurnos.index') }}" class="btn btn-default">Cancelar</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/parametrizacion_turnos/fields.blade.php
@isset($parametrizacionTurno)
    @if($parametrizacionTurno->generado)
        <!-- <p class="text-primary">GENERADO</p> -->
        <div class="p-3 mb-2 bg-success text-white">TURNOS GENERADOS</div>
    @else        
        <div class="p-3 mb-2 bg-success text-white">TURNOS SIN GENERAR</div>
    @endif
@endisset
<div class="form-group col-sm-12">
    <label class="control-label" for="semana">Dias:</label>

    @isset($parametrizacionTurno)
        @livewire('selector-dias-semana', [ 'selectedDays' => $parametrizacionTurno->dias ])
    @else
        @livewire('selector-dias-semana')
    @endisset
</div>

<!-- Fecha Desde Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fecha_desde', 'Fecha Desde:') !!}
    @isset($parametrizacionTurno)
        {!! Form::date('fecha_desde', $parametrizacionTurno->fecha_desde, ['class' => 'form-control','id'=>'fecha_desde', 'min'=>date('Y-m-d')]) !!}
    @else
        {!! Form::date('fecha_desde', null, ['class' => 'form-control','id'=>'fecha_desde', 'min'=>date('Y-m-d')]) !!}
    @endisset
</div>

<!-- Fecha Hasta Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fecha_hasta', 'Fecha Hasta:') !!}
    @isset($parametrizacionTurno)
        {!! Form::date('fecha_hasta', $parametrizacionTurno->fecha_hasta, ['class' => 'form-control','id'=>'fecha_hasta', 'min'=>date('Y-m-d')]) !!}
    @else
        {!! Form::date('fecha_hasta', null, ['class' => 'form-control','id'=>'fecha_hasta', 'min'=>date('Y-m-d')]) !!}
    @endisset
</div>

<!-- Hora Desde Field -->
<div class="form-group col-sm-6">
    {!! Form::label('hora_desde', 'Hora Desde:') !!}
    {!! Form::time('hora_desde', null, ['class' => 'form-control']) !!}
</div>

<!-- Hora Hasta Field -->
<div class="form-group col-sm-6">
    {!! Form::label('hora_hasta', 'Hora Hasta:') !!}
    {!! Form::time('hora_hasta', null, ['class' => 'form-control']) !!}
</div>

<!-- Duracion Turno Field -->
<div class="form-group col-sm-6">
    {!! Form::label('duracion_turno', 'Duración del Turno:') !!}
    {!! Form::number('duracion_turno', null, ['class' => 'form-control']) !!}
</div>

<!-- Sobreturnos Field -->
<!-- <div class="form-group col-sm-6">
    {!! Form::label('sobreturnos', 'Sobreturnos:') !!}
    {!! Form::number('sobreturnos', null, ['class' => 'form-control']) !!}
</div>
 -->

<!-- Id Sucursal Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_sucursal', 'Sucursal:') !!}    
    {!! Form::select('id_sucursal', $sucursales, null, ['class' => 'form-control custom-select']) !!}
</div>

@isset($parametrizacionTurno)
    @livewire('profesional-especialidad', [
        'selectedProfesional' => $parametrizacionTurno->id_profesional,
        'selectedEspecialidad' => $parametrizacionTurno->id_especialidad,        
    ])
@else
    @livewire('profesional-especialidad')
@endisset

resources/views/parametrizacion_turnos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Parametrización de Turnos</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('parametrizacionTurnos.create') }}">
                        Nuevo
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('parametrizacion_turnos.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/parametrizacion_turnos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Parametrización Turno Detalle</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('parametrizacionTurnos.index') }}">
                        Volver
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('parametrizacion_turnos.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/parametrizacion_turnos/table.blade.php
<div class="table-responsive">
    <table class="table" id="parametrizacionTurnos-table">
        <thead>
        <tr>
            <th>Días</th>
            <th>Fecha Desde</th>
            <th>Fecha Hasta</th>
            <th>Hora Desde</th>
            <th>Hora Hasta</th>
            <th>Duración del Turno</th>            
            <th>Sucursal</th>
            <th>Profesional</th>
            <th>Especialidad</th>
            <th>Generado</th>
            <th colspan="3">Acción</th>
        </tr>
        </thead>
        <tbody>
        @foreach($parametrizacionTurnos as $parametrizacionTurno)
            <tr>
                <td>
                    <ul>
                    @foreach($parametrizacionTurno->dias() as $dia)
                        <li>
                            {{ $dia->abreviatura }}
                            @if(!$loop->last)
                            <!-- / -->
                            @endif
                        </li>
                    @endforeach
                    </ul>
                </td>
                <td>{{ $parametrizacionTurno->fecha_desde->format('d/m/Y') }}</td>
                <td>{{ $parametrizacionTurno->fecha_hasta->format('d/m/Y') }}</td>
                <td>{{ Str::limit($parametrizacionTurno->hora_desde, 5, '') }}</td>
                <td>{{ Str::limit($parametrizacionTurno->hora_hasta, 5, '') }}</td>
                <td>{{ $parametrizacionTurno->duracion_turno }}</td>                
                <td>{{ $parametrizacionTurno->sucursal->nombre }}</td>
                <td>{{ $parametrizacionTurno->profesional->full_name }}</td>
                <td>{{ $parametrizacionTurno->especialidad->descripcion }}</td>
                <td>@if($parametrizacionTurno->generado)
                        <p class="text-success">SI</p> 
                    @else 
                        <p class="text-danger">NO</p>
                    @endif
                </td>
                <td width="120">
                    {!! Form::open(['route' => ['parametrizacionTurnos.destroy', $parametrizacionTurno->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('parametrizacionTurnos.show', [$parametrizacionTurno->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('parametrizacionTurnos.edit', [$parametrizacionTurno->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        <a href="{{ route('parametrizacionTurnos.visualizarTurnos', [$parametrizacionTurno->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="fas fa-cog" title="Generar"></i>
                        </a>                        
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Esta seguro?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/parametrizacion_turnos/table_turnos.blade.php
<div class="table-responsive">
    <table class="table" id="parametrizacionTurnos-table">
        <thead>
        <tr>
        	<th>#</th>
            <th>Fecha</th>
            <th>Hora Desde</th>
            <th>Hora Hasta</th>
            <th>Estado</th>
            <th>Sobreturnos</th>                        
            <th>Fecha Generación</th>
        </tr>
        </thead>
        <tbody>
        @foreach($turnos as $turno)
            <tr>
            	<td>{{ $loop->index+1 }}</td>
                <td>{{ $turno->fecha->format('d/m/Y') }}</td>                
                <td>{{ $turno->hora_desde }}</td>
                <td>{{ $turno->hora_hasta }}</td>                
                <td>{{ $turno->estado }}</td>
                <td>{{ $turno->sobreturnos }}</td>
                <td>{{ $turno->fecha_generacion }}</td>                
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/parametrizacion_turnos/visualizar_turnos.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Previsualización de Turnos a generar</h1>
                </div>
                <div class="col-sm-6">
                    @if(!$parametrizacionTurno->generado) 
                    <a class="btn btn-primary float-right"
                       href="{{ route('parametrizacionTurnos.generarTurnos', [$parametrizacionTurno->id]) }}">
                        Generar
                    </a>
                    @endif
                    <a class="btn btn-default float-right"
                       href="{{ route('parametrizacionTurnos.index') }}">
                        Volver
                    </a>                                        
                    
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">            
            
            <!-- Fecha Desde Field -->
            <div class="col-sm-12">
                {!! Form::label('estado', 'Estado Parametrización:') !!}
                @if($parametrizacionTurno->generado) 
                    <span class="text-success">GENERADO</span> 
                @else 
                    <span class="text-danger">SIN GENERAR</span>
                @endif                                
            </div>

            <!-- Fecha Desde Field -->
            <div class="col-sm-12">
                {!! Form::label('hora_desde', 'Fecha Desde:') !!}
                {{ $parametrizacionTurno->fecha_desde->format('d/m/Y') }}
            </div>

             <!-- Fecha Hasta Field -->
            <div class="col-sm-12">
                {!! Form::label('hora_desde', 'Fecha Hasta:') !!}
                {{ $parametrizacionTurno->fecha_hasta->format('d/m/Y') }}
            </div>


            <!-- Sucursal Field -->
            <div class="col-sm-12">
                {!! Form::label('fecha_desde', 'Sucursal:') !!}
                {{ $parametrizacionTurno->sucursal->nombre }}
            </div>

            <!-- Profesional Field -->
            <div class="col-sm-12">
                {!! Form::label('fecha_hasta', 'Profesional:') !!}
                {{ $parametrizacionTurno->profesional->full_name }}
            </div>

            <!-- Especialidad Field -->
            <div class="col-sm-12">
                {!! Form::label('hora_desde', 'Especialidad:') !!}
                {{ $parametrizacionTurno->especialidad->descripcion }}
            </div>

             <!-- Duracion Field -->
            <div class="col-sm-12">
                {!! Form::label('hora_desde', 'Duración:') !!}
                {{ $parametrizacionTurno->duracion_turno }}
            </div>           

            <div class="col-sm-12">
                @livewire('selector-dias-semana', [ 'selectedDays' => $parametrizacionTurno->dias, 'editable' => false ])
            </div>

            <!-- Cant Dias Field -->
            <div class="col-sm-12">
                {!! Form::label('cantidad_dias', 'Cantidad de días a generar:') !!}
                {{ $turnos->groupBy('fechaText')->count() }}
            </div>

            <div class="card-body p-0">
                @include('parametrizacion_turnos.table_turnos_agrupado')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection