routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('rubros', App\Http\Controllers\RubroController::class);


Route::resource('empresas', App\Http\Controllers\EmpresaController::class);


Route::resource('profesions', App\Http\Controllers\ProfesionController::class);


Route::resource('profesionals', App\Http\Controllers\ProfesionalController::class);


Route::resource('especialidads', App\Http\Controllers\EspecialidadController::class);


Route::resource('sucursals', App\Http\Controllers\SucursalController::class);


Route::resource('feriados', App\Http\Controllers\FeriadoController::class);


Route::resource('parametrizacionTurnos', App\Http\Controllers\ParametrizacionTurnoController::class);

Route::resource('dias', App\Http\Controllers\DiaController::class);

Route::get('parametrizacionTurnos/{id}/visualizarTurnos', [App\Http\Controllers\ParametrizacionTurnoController::class,'visualizarTurnos'])
    ->name('parametrizacionTurnos.visualizarTurnos');

Route::get('parametrizacionTurnos/{id}/generarTurnos', [App\Http\Controllers\ParametrizacionTurnoController::class,'generarTurnos'])
    ->name('parametrizacionTurnos.generarTurnos');    


Route::resource('turnos', App\Http\Controllers\TurnoController::class);


Route::resource('tipoInstalacions', App\Http\Controllers\TipoInstalacionController::class);


Route::resource('instalacions', App\Http\Controllers\InstalacionController::class);


Route::resource('reservas', App\Http\Controllers\ReservaController::class);

Route::post('reservas/{id}/cancelar', [App\Http\Controllers\ReservaController::class,'cancelar'])->name('reservas.cancelar'); 

Route::resource('agenda', App\Http\Controllers\AgendaController::class);

Route::get('agenda/{id}/ausente', [App\Http\Controllers\AgendaController::class,'ausente'])->name('agenda.ausente');

Route::get('agenda/{id}/presente', [App\Http\Controllers\AgendaController::class,'presente'])->name('agenda.presente');        


Route::resource('users', App\Http\Controllers\UserController::class)->middleware('auth');

app/Models/TipoInstalacion.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class TipoInstalacion
 * @package App\Models
 * @version November 28, 2021, 9:49 pm UTC
 *
 * @property string $descripcion
 * @property boolean $activo
 * @property int $id_empresa
 */
class TipoInstalacion extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'tipo_instalaciones';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'descripcion',
        'activo',
        'id_empresa'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'descripcion' => 'string',
        'activo' => 'boolean',
        'id_empresa' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'descripcion' => 'required|max:100',        
    ];

    
}

app/Http/Controllers/TipoInstalacionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTipoInstalacionRequest;
use App\Http\Requests\UpdateTipoInstalacionRequest;
use App\Repositories\TipoInstalacionRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use Auth;

class TipoInstalacionController extends AppBaseController
{
    /** @var  TipoInstalacionRepository */
    private $tipoInstalacionRepository;

    public function __construct(TipoInstalacionRepository $tipoInstalacionRepo)
    {
        $this->tipoInstalacionRepository = $tipoInstalacionRepo;
    }

    /**
     * Display a listing of the TipoInstalacion.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $tipoInstalacions = $this->tipoInstalacionRepository->all();

        return view('tipo_instalacions.index')
            ->with('tipoInstalacions', $tipoInstalacions);
    }

    /**
     * Show the form for creating a new TipoInstalacion.
     *
     * @return Response
     */
    public function create()
    {
        return view('tipo_instalacions.create');
    }

    /**
     * Store a newly created TipoInstalacion in storage.
     *
     * @param CreateTipoInstalacionRequest $request
     *
     * @return Response
     */
    public function store(CreateTipoInstalacionRequest $request)
    {
        $input = $request->all();

        $user=Auth::user();

        if (empty($user->id_empresa)) {
            Flash::error('El usuario no tiene empresa definida');

            return redirect(route('tipoInstalacions.index'));
        }

        $input['id_empresa'] = $user->id_empresa;        

        $tipoInstalacion = $this->tipoInstalacionRepository->create($input);

        Flash::success('Tipo de Instalación guardado de forma correcta.');

        return redirect(route('tipoInstalacions.index'));
    }

    /**
     * Display the specified TipoInstalacion.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $tipoInstalacion = $this->tipoInstalacionRepository->find($id);

        if (empty($tipoInstalacion)) {
            Flash::error('Tipo de Instalación no encontrado');

            return redirect(route('tipoInstalacions.index'));
        }

        return view('tipo_instalacions.show')->with('tipoInstalacion', $tipoInstalacion);
    }

    /**
     * Show the form for editing the specified TipoInstalacion.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $tipoInstalacion = $this->tipoInstalacionRepository->find($id);

        if (empty($tipoInstalacion)) {
            Flash::error('Tipo de Instalación no encontrado');

            return redirect(route('tipoInstalacions.index'));
        }

        return view('tipo_instalacions.edit')->with('tipoInstalacion', $tipoInstalacion);
    }

    /**
     * Update the specified TipoInstalacion in storage.
     *
     * @param int $id
     * @param UpdateTipoInstalacionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTipoInstalacionRequest $request)
    {
        $tipoInstalacion = $this->tipoInstalacionRepository->find($id);

        if (empty($tipoInstalacion)) {
            Flash::error('Tipo de Instalación no encontrado');

            return redirect(route('tipoInstalacions.index'));
        }

        $data = $request->all();

        //$data['activo'] = isset($data['activo']);   //si no esta checheado no me lo manda en el request

        $tipoInstalacion = $this->tipoInstalacionRepository->update($data, $id);

        Flash::success('Tipo de Instalación actualizado de forma correcta.');

        return redirect(route('tipoInstalacions.index'));
    }

    /**
     * Remove the specified TipoInstalacion from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $tipoInstalacion = $this->tipoInstalacionRepository->find($id);

        if (empty($tipoInstalacion)) {
            Flash::error('Tipo de Instalación no encontrado');

            return redirect(route('tipoInstalacions.index'));
        }

        $this->tipoInstalacionRepository->delete($id);

        Flash::success('Tipo Instalacion eliminado de forma correcta.');

        return redirect(route('tipoInstalacions.index'));
    }
}

resources/views/tipo_instalacions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Crear Tipo de Instalación</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'tipoInstalacions.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('tipo_instalacions.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('tipoInstalacions.index') }}" class="btn btn-default">Cancelar</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/tipo_instalacions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Editar Tipo Instalación</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($tipoInstalacion, ['route' => ['tipoInstalacions.update', $tipoInstalacion->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('tipo_instalacions.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('tipoInstalacions.index') }}" class="btn btn-default">Cancelar</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/tipo_instalacions/fields.blade.php
<!-- Descripcion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('descripcion', 'Descripción:') !!}
    {!! Form::text('descripcion', null, ['class' => 'form-control','max' => '100', 'required']) !!}
</div>

<!-- Activo Field -->
<div class="form-group col-sm-12">
    <div class="form-check">
        {!! Form::hidden('activo', 0, ['class' => 'form-check-input']) !!}
        {!! Form::checkbox('activo', '1', null, ['class' => 'form-check-input']) !!}
        {!! Form::label('activo', 'Activo', ['class' => 'form-check-label']) !!}
    </div>
</div>

resources/views/tipo_instalacions/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Tipos de Instalaciones</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('tipoInstalacions.create') }}">
                        Nuevo
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('tipo_instalacions.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/tipo_instalacions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Tipo de Instalación</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('tipoInstalacions.index') }}">
                        Volver
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('tipo_instalacions.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tipo_instalacions/show_fields.blade.php
<!-- Descripcion Field -->
<div class="col-sm-12">
    {!! Form::label('descripcion', 'Descripción:') !!}
    <p>{{ $tipoInstalacion->descripcion }}</p>
</div>

<!-- Activo Field -->
<div class="col-sm-12">
    {!! Form::label('activo', 'Activo:') !!}
    <p>{{ $tipoInstalacion->activo }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Creado el:') !!}
    <p>{{ $tipoInstalacion->created_at->format('d/m/Y h:i') }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Actualizado el:') !!}
    <p>{{ $tipoInstalacion->updated_at->format('d/m/Y h:i') }}</p>
</div>

resources/views/tipo_instalacions/table.blade.php
<div class="table-responsive">
    <table class="table" id="tipoInstalacions-table">
        <thead>
        <tr>
            <th>Descripción</th>
            <th>Activo</th>
            <th colspan="3">Acción</th>
        </tr>
        </thead>
        <tbody>
        @foreach($tipoInstalacions as $tipoInstalacion)
            <tr>
            <td>{{ $tipoInstalacion->descripcion }}</td>
            <td>@if($tipoInstalacion->activo) SI @else NO @endif</td>
            <td width="120">
                {!! Form::open(['route' => ['tipoInstalacions.destroy', $tipoInstalacion->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{{ route('tipoInstalacions.show', [$tipoInstalacion->id]) }}"
                       class='btn btn-default btn-xs'>
                        <i class="far fa-eye"></i>
                    </a>
                    <a href="{{ route('tipoInstalacions.edit', [$tipoInstalacion->id]) }}"
                       class='btn btn-default btn-xs'>
                        <i class="far fa-edit"></i>
                    </a>
                    {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Esta seguro?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>