routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('rubros', App\Http\Controllers\RubroController::class);


Route::resource('empresas', App\Http\Controllers\EmpresaController::class);


Route::resource('profesions', App\Http\Controllers\ProfesionController::class);


Route::resource('profesionals', App\Http\Controllers\ProfesionalController::class);


Route::resource('especialidads', App\Http\Controllers\EspecialidadController::class);


Route::resource('sucursals', App\Http\Controllers\SucursalController::class);


Route::resource('feriados', App\Http\Controllers\FeriadoController::class);


Route::resource('parametrizacionTurnos', App\Http\Controllers\ParametrizacionTurnoController::class);

Route::resource('dias', App\Http\Controllers\DiaController::class);

Route::get('parametrizacionTurnos/{id}/visualizarTurnos', [App\Http\Controllers\ParametrizacionTurnoController::class,'visualizarTurnos'])
    ->name('parametrizacionTurnos.visualizarTurnos');

Route::get('parametrizacionTurnos/{id}/generarTurnos', [App\Http\Controllers\ParametrizacionTurnoController::class,'generarTurnos'])
    ->name('parametrizacionTurnos.generarTurnos');    


Route::resource('turnos', App\Http\Controllers\TurnoController::class);


Route::resource('tipoInstalacions', App\Http\Controllers\TipoInstalacionController::class);


Route::resource('instalacions', App\Http\Controllers\InstalacionController::class);


Route::resource('reservas', App\Http\Controllers\ReservaController::class);

Route::post('reservas/{id}/cancelar', [App\Http\Controllers\ReservaController::class,'cancelar'])->name('reservas.cancelar'); 

Route::resource('agenda', App\Http\Controllers\AgendaController::class);

Route::get('agenda/{id}/ausente', [App\Http\Controllers\AgendaController::class,'ausente'])->name('agenda.ausente');

Route::get('agenda/{id}/presente', [App\Http\Controllers\AgendaController::class,'presente'])->name('agenda.presente');        


Route::resource('users', App\Http\Controllers\UserController::class)->middleware('auth');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ config('app.name') }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link rel="icon" type="image/png" href="favicon.ico">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap4-toggle/3.6.1/bootstrap4-toggle.min.css"
          integrity="sha512-EzrsULyNzUc4xnMaqTrB4EpGvudqpetxG/WNjCpG6ZyyAGxeB6OBF9o246+mwx3l/9Cn838iLIcrxpPHTiygAA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- AdminLTE -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.1.0/css/adminlte.min.css"
          integrity="sha512-mxrUXSjrxl8vm5GwafxcqTrEwO1/oBNU25l20GODsysHReZo4uhVISzAKzaABH6/tTfAxZrY2FprmeAP5UZY8A=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/icheck-bootstrap/3.0.1/icheck-bootstrap.min.css"
          integrity="sha512-8vq2g5nHE062j3xor4XxPeZiPjmRDh6wlufQlfC6pdQ/9urJkU07NM0tEREeymP++NczacJ/Q59ul+/K2eYvcg=="
          crossorigin="anonymous"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"
          integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw=="
          crossorigin="anonymous"/>

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css"
          integrity="sha512-aEe/ZxePawj0+G2R+AaIxgrQuKT68I28qh+wgLrcAJOz3rxCP+TwrK5SPN+E5I+1IQjNtcfvb96HDagwrKRdBw=="
          crossorigin="anonymous"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" 
          integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" 
          crossorigin="anonymous">

    <link href="{{ URL::asset('css/app.css') }}" rel="stylesheet">

    @livewireStyles

    @stack('third_party_stylesheets')

    @stack('page_css')
</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <!-- Main Header -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown user-menu">
                <a id="dropdownMenuLink" href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" >
                    <img src="https://assets.infyom.com/logo/blue_logo_150x150.png"
                         class="user-image img-circle elevation-2" alt="User Image">
                    <span class="d-none d-md-inline">{{ Auth::user()->name }}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenuLink">
                    <!-- User image -->
                    <li class="user-header bg-primary dropdown-item" >
                        <img src="https://assets.infyom.com/logo/blue_logo_150x150.png"
                             class="img-circle elevation-2"
                             alt="Imagen de usuario">
                        <p>
                            {{ Auth::user()->name }}
                            <small>Miembro desde {{ Auth::user()->created_at->format('M. Y') }}</small>
                        </p>
                    </li>
                    <!-- Menu Footer-->
                    <li class="user-footer dropdown-item">
                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                        <a href="#" class="btn btn-default btn-flat float-right"
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            Cerrar sesión
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>

    <!-- Left side column. contains the logo and sidebar -->
@include('layouts.sidebar')

<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <section class="content">
            @yield('content')
        </section>
    </div>

    <!-- Main Footer -->
    <footer class="main-footer">
        <div class="float-right d-none d-sm-block">
            <b>Versión</b> {{ env('APP_VERSION') }}
        </div>
        <strong>
           Copyright &copy; <a href="{{ env('COPYRIGHT_LINK') }}">{{ env('COPYRIGHT_NAME') }}</a>.
        </strong>
        Todos los derechos reservados.
    </footer>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>

<!-- AdminLTE App -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.1.0/js/adminlte.min.js"
        integrity="sha512-AJUWwfMxFuQLv1iPZOTZX0N/jTCIrLxyZjTRKQostNU71MzZTEPHjajSK20Kj1TwJELpP7gl+ShXw5brpnKwEg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"
        integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"
        integrity="sha512-GDey37RZAxFkpFeJorEUwNoIbkTwsyC736KNSYucu1WJWFK9qTdzYub8ATxktr6Dwke7nbFaioypzbDOQykoRg=="
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"
        integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A=="
        crossorigin="anonymous"></script>
        
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/1.3/bootstrapSwitch.min.js"
        integrity="sha512-DAc/LqVY2liDbikmJwUS1MSE3pIH0DFprKHZKPcJC7e3TtAOzT55gEMTleegwyuIWgCfOPOM8eLbbvFaG9F/cA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" 
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/jquery.appendgrid@2/dist/AppendGrid.js"></script>

<script>
    $(function () {
        bsCustomFileInput.init();
    });

    $("input[data-bootstrap-switch]").each(function () {
        $(this).bootstrapSwitch('state', $(this).prop('checked'));
    });
</script>

@stack('third_party_scripts')

@stack('page_scripts')

@livewireScripts
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.bootstrap4.min.css">
<link href="{{ URL::asset('css/datatables.css') }}" rel="stylesheet">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
<li class="nav-item has-treeview">
    <a href="#"
       class="nav-link">
        <i class="fas fa-cog"></i>
        <p>Configuración</p>
        <i class="right fas fa-angle-left"></i>
    </a>
    <ul class="nav nav-treeview">
  
        <li class="nav-item">
            <a href="{{ route('rubros.index') }}"
               class="nav-link {{ Request::is('rubros*') ? 'active' : '' }}">
               <i class="fas fa-registered"></i>
                <p>Rubros</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="{{ route('empresas.index') }}"
               class="nav-link {{ Request::is('empresas*') ? 'active' : '' }}">
                <i class="far fa-building"></i>
                <p>Empresas</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="{{ route('profesions.index') }}"
               class="nav-link {{ Request::is('profesions*') ? 'active' : '' }}">
               <i class="fas fa-stethoscope"></i>
                <p>Profesiones</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="{{ route('especialidads.index') }}"
               class="nav-link {{ Request::is('especialidads*') ? 'active' : '' }}">
                <i class="fas fa-book-medical"></i>
                <p>Especialidades</p>
            </a>
        </li>

    </ul>
</li>



<li class="nav-item">
    <a href="{{ route('profesionals.index') }}"
       class="nav-link {{ Request::is('profesionals*') ? 'active' : '' }}">
        <i class="fas fa-user-tie"></i>
        <p>Profesionales</p>
    </a>
</li>



<li class="nav-item">
    <a href="{{ route('sucursals.index') }}"
       class="nav-link {{ Request::is('sucursals*') ? 'active' : '' }}">
        <i class="fas fa-hospital-alt"></i>        
        <p>Sucursales</p>
    </a>
    
</li>


<li class="nav-item">
    <a href="{{ route('feriados.index') }}"
       class="nav-link {{ Request::is('feriados*') ? 'active' : '' }}">
        <i class="fas fa-calendar-times"></i>
        <p>Feriados</p>
    </a>
</li>


<li class="nav-item">
    <a href="{{ route('parametrizacionTurnos.index') }}"
       class="nav-link {{ Request::is('parametrizacionTurnos*') ? 'active' : '' }}">
        <i class="far fa-calendar-plus"></i>
        <p>Parametrizacion Turnos</p>
    </a>
</li>


<li class="nav-item d-none">
    <a href="{{ route('dias.index') }}"
       class="nav-link {{ Request::is('dias*') ? 'active' : '' }}">
        <p>Dias</p>
    </a>
</li>


<li class="nav-item">
    <a href="{{ route('turnos.index') }}"
       class="nav-link {{ Request::is('turnos*') ? 'active' : '' }}">
        <i class="fas fa-calendar-alt"></i>
        <p>Turnos</p>
    </a>
</li>
<!-- <i class="fas fa-calendar-check"></i> -->

<!-- <li class="nav-item">
    <a href="{{ route('tipoInstalacions.index') }}"
       class="nav-link {{ Request::is('tipoInstalacions*') ? 'active' : '' }}">
        <p>Tipos de Instalaciones</p>
    </a>
</li>


<li class="nav-item">
    <a href="{{ route('instalacions.index') }}"
       class="nav-link {{ Request::is('instalacions*') ? 'active' : '' }}">
        <p>Instalacions</p>
    </a>
</li> -->


<li class="nav-item">
    <a href="{{ route('reservas.index') }}"
       class="nav-link {{ Request::is('reservas*') ? 'active' : '' }}">
       <i class="fas fa-calendar-alt"></i>
        <p>Reservas</p>
    </a>
</li>


<li class="nav-item">
    <a href="{{ route('agenda.index') }}"
       class="nav-link {{ Request::is('agenda*') ? 'active' : '' }}">
        <i class="fas fa-calendar-alt"></i>
        <p>Agenda</p>
    </a>
</li>

<li class="nav-item">
    <a href="{{ route('users.index') }}"
       class="nav-link {{ Request::is('users*') ? 'active' : '' }}">
        <i class="fa fa-user"></i>
        <p>Usuarios</p>
    </a>
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{{ url('/home') }}" class="brand-link">
        <img src="https://assets.infyom.com/logo/blue_logo_150x150.png"
             alt="{{ config('app.name') }} Logo"
             class="brand-image img-circle elevation-3">
        <span class="brand-text font-weight-light">{{ config('app.name') }}</span>
    </a>
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar nav-child-indent  flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @include('layouts.menu')
            </ul>
        </nav>
    </div>
</aside>